config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { registrations: 'user_registrations' }
  devise_scope :user do
    get 'worker/sign_up', to: 'user_registrations#new', user: { rolable_type: 'worker' }
    post 'worker/sign_up', to: 'user_registrations#create', user: { rolable_type: 'worker' }
    get 'worker/edit', to: 'user_registrations#edit', user: { rolable_type: 'worker' }
    put 'worker/edit', to: 'user_registrations#update', user: { rolable_type: 'worker' }
    
    get 'customer/sign_up', to: 'user_registrations#new', user: { rolable_type: 'customer' }
    post 'customer/sign_up', to: 'user_registrations#create', user: { rolable_type: 'customer' }
    get 'customer/edit', to: 'user_registrations#edit', user: { rolable_type: 'customer' }
    put 'customer/edit', to: 'user_registrations#update', user: { rolable_type: 'customer' }
  end
  
  resources :workers, only: [:show, :update, :destroy] do
    get :jobs
  end

  resources :customers, only: [:update, :destroy] do
    get :jobs
    post :jobs
  end

  resources :jobs, only: [:new, :create]
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_one :user, as: :rolable, dependent: :destroy
  has_many :jobs
  has_many :workers, through: :jobs

  def self.create(name:, email:, password:)
    Customer.new(name: name, user: User.new(email: email, password: password))
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :customer
  belongs_to :worker

  def self.create(worker:, customer:, description:, start_date:, end_date:)
    Job.new worker: worker, customer: customer, description: description, start_date: start_date, end_date: end_date
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  belongs_to :rolable, polymorphic: true
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  has_one :user, as: :rolable, dependent: :destroy
  has_many :jobs
  has_many :customers, through: :jobs

  scope :any_skills, -> (skills){where('skills && ARRAY[?]', skills)}
  scope :all_skills, -> (skills){where('skills @> ARRAY[?]', skills)}

  def self.create(name:, email:, password:, skills:)
    Worker.new(name: name, skills: skills, user: User.new(email: email, password: password))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  include WorkersHelper

  helper_method :display_skills
  before_filter :authenticate_user!
  after_action :verify_authorized

  def jobs
    @customer = Customer.find(params[:customer_id])
    authorize @customer
    @jobs = @customer.jobs
    if params[:skills]
      skills = parse_skills(params[:skills])
      @workers = Worker.all_skills(skills)
      @skills = skills
    else
      @workers = []
      @skills = []
    end
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def new
    customer = current_user.rolable
    authorize customer, :create_new_job?

    @job = Job.new
    @worker = Worker.find(params[:wid])
  end

  def create
    customer = current_user.rolable
    authorize customer, :create_new_job?

    job = Job.new(secure_params)
    job.customer_id = current_user.rolable_id
    if job.save
      redirect_to customer_jobs_path(current_user.rolable_id), notice: 'Job created.'
    else
      redirect_to customer_jobs_path(current_user.rolable_id), alert: 'Unable to create job.'
    end
  end

  def secure_params
    params.require(:job).permit(:description, :start_date, :end_date, :worker_id)
  end
end

app/controllers/user_registrations_controller.rb
class UserRegistrationsController < Devise::RegistrationsController
  include WorkersHelper

  helper_method :display_skills
  before_filter :authenticate_user!, only: [:edit, :update]
  after_action :verify_authorized, only: [:edit, :update]

  def edit
    authorize current_user.rolable
  end
  
  def create
    build_resource(sign_up_params)

    child_class = params[:user][:rolable_type].camelize.constantize

    # split skills into array before create
    if child_class.to_s.underscore == 'worker'
      params[child_class.to_s.underscore][:skills] = parse_skills(params[child_class.to_s.underscore][:skills])
    end

    resource.rolable = child_class.new(params.require(child_class.to_s.underscore).permit!)

    valid = resource.valid?
    valid = resource.rolable.valid? && valid

    if valid
      resource_saved = resource.save
      yield resource if block_given?
      if resource_saved
        if resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_flashing_format?
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        @validatable = devise_mapping.validatable?
        if @validatable
          @minimum_password_length = resource_class.password_length.min
        end
        respond_with resource
      end
    else
      clean_up_passwords resource
      @validatable = devise_mapping.validatable?
      if @validatable
        @minimum_password_length = resource_class.password_length.min
      end
      respond_with resource
    end
  end

  def update
    authorize current_user.rolable

    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    child_class = params[:user][:rolable_type].camelize.constantize

    # split skills into array before update
    if child_class.to_s.underscore == 'worker'
      params[child_class.to_s.underscore][:skills] = parse_skills(params[child_class.to_s.underscore][:skills])
    end

    rolable_updated = resource.rolable.update_attributes(params.require(child_class.to_s.underscore).permit!)

    resource_updated = update_resource(resource, account_update_params) && rolable_updated
    yield resource if block_given?
    if resource_updated
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, bypass: true
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def show
    @worker = Worker.find_by_id(params[:id])
    unless @worker
      redirect_to workers_path, alert: "Non-existig user."
    else
      authorize @worker
    end
  end

  def jobs
    worker = Worker.find(params[:worker_id])
    authorize worker
    @jobs = worker.jobs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def skillz_devise_error_messages!
    return "" if resource.errors.empty? && resource.rolable.errors.empty?

    messages = rolable_messages = ""

    if !resource.errors.empty?
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    end

    if !resource.rolable.errors.empty?
      rolable_messages = resource.rolable.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    end

    messages = messages + rolable_messages   
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count + resource.rolable.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
    <h2>#{sentence}</h2>
    <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/workers_helper.rb
module WorkersHelper
  def display_skills(skills, c = ',')
    skills.join(c)
  end

  def parse_skills(text)
    text.split(',')
  end
end

app/views/customers/jobs.html.erb
<h1>Find workers</h1>
<%= form_tag({}, class: 'form-inline') do %>
  <%= label_tag :skills, "Search for skills:" %>
  <%= text_field_tag :skills, display_skills(@skills), class: 'form-control', placeholder: 'comma-delimited list of skills', style: 'width:300px' %>
  <%= submit_tag "Search", class: "btn btn-primary glyphicon glyphicon-search" %>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Skills</th>
    </tr>
  </thead>
  <tbody>
    <% @workers.each do |worker| %>
    <tr>
      <td><%= worker.name %></td>
      <td><%= display_skills(worker.skills) %></td>
      <td><%= link_to 'Hire', new_job_path(wid: worker.id), class: "btn btn-primary btn-xs" %>
    </tr>
    <% end %>
  </tbody>
</table>

<h1>Jobs history</h1>
<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Worker</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
    <tr>
      <td><%= job.description %></td>
      <td><%= job.start_date %></td>
      <td><%= job.end_date %></td>
      <td><%= link_to job.worker.name, worker_path(job.worker.id) %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h1>HTML Ipsum Presents</h1>
         
<p><strong>Pellentesque habitant morbi tristique</strong> senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.</em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae</code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href="#">Donec non enim</a> in turpis pulvinar facilisis. Ut felis.</p>

<h2>Header Level 2</h2>
         
<ol>
   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
   <li>Aliquam tincidunt mauris eu risus.</li>
</ol>

<blockquote><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in mi at felis aliquet congue. Ut a est eget ligula molestie gravida. Curabitur massa. Donec eleifend, libero at sagittis mollis, tellus est malesuada tellus, at luctus turpis elit sit amet quam. Vivamus pretium ornare est.</p></blockquote>

<h3>Header Level 3</h3>

<ul>
   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
   <li>Aliquam tincidunt mauris eu risus.</li>
</ul>

<pre><code>
#header h1 a { 
  display: block; 
  width: 300px; 
  height: 80px; 
}
</code></pre>

<dl>
   <dt>Definition list</dt>
   <dd>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
commodo consequat.</dd>
   <dt>Lorem ipsum dolor sit amet</dt>
   <dd>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna 
aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
commodo consequat.</dd>
</dl>

app/views/jobs/new.html.erb
<h3>Worker Details</h3>
<p>Name: <%= @worker.name %></p>
<p>Email: <%= @worker.user.email %></p>
<p>Skills: <%= display_skills(@worker.skills, ', ') %></p>

<h3>Create a job</h3>
<%= form_for(@job, url: { action: 'create' }, html: { :role => 'form'}) do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :start_date %>
    <%= f.date_field :start_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :end_date %>
    <%= f.date_field :end_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :worker_id, value: @worker.id %>
  </div>
  <%= f.submit 'Create', :class => 'button btn-primary right' %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <span class="glyphicon glyphicon-certificate" aria-hidden="true"></span>
        Skillz
      </a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <% if current_user.rolable_type == 'Worker' %>
        <li><%= link_to "Jobs History", worker_jobs_path(current_user.rolable_id) %></li>
        <% else %>
        <li><%= link_to "Jobs History", customer_jobs_path(current_user.rolable_id) %></li>
        <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <% if current_user.rolable_type == 'Worker' %>
  <li><%= link_to "Edit #{current_user.email}", worker_edit_path %></li>
  <% else %>
  <li><%= link_to "Edit #{current_user.email}", customer_edit_path %></li>
  <% end %>
  </li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Worker sign up', worker_sign_up_path %></li>
  <li><%= link_to 'Customer sign up', customer_sign_up_path %></li>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Skillz - The Jobs Board" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Skillz is the best jobs board in the world." %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/user_registrations/_customer_fields.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

app/views/user_registrations/_worker_fields.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :skills %>
  <%= f.text_field :skills, class: 'form-control', value: display_skills(@user.rolable.skills) %>
</div>

app/views/user_registrations/edit.html.erb
<div class="authform">
  <h3>Edit <%= resource_name.to_s.humanize %></h3>
  <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put, :role => 'form'}) do |f| %>
    <%= skillz_devise_error_messages! %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <fieldset>
      <p>Leave these fields blank if you don't want to change your password.</p>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, :autocomplete => 'off', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </fieldset>
    <fieldset>
      <p>You must enter your current password to make changes.</p>
      <div class="form-group">
        <%= f.label :current_password %>
        <%= f.password_field :current_password, class: 'form-control' %>
      </div>
    </fieldset>
    <fieldset>
      <%= fields_for resource.rolable do |rf| %>
        <% child_class_name = resource.rolable_type.downcase.camelize %>
        <% render :partial => "#{child_class_name.underscore}_fields", :locals => { :f => rf } %>
      <% end %>
    </fieldset>
    <%= hidden_field :user, :rolable_type, value: resource.rolable_type.downcase.camelize %>
    <%= f.submit 'Update', :class => 'button right' %>
  <% end %>
</div>
<div class="authform">
<h3>Cancel Account</h3>
<p>Unhappy? We'll be sad to see you go.</p>
<%= button_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button right' %>
</div>

app/views/user_registrations/new.html.erb
<div class="authform">
  <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :role => 'form'}) do |f| %>
    <h3>Sign up <%= params[:user][:rolable_type].downcase.camelize %></h3>
    <%
      params[:user][:rolable_type] ||= 'worker'

      if ["worker", "customer"].include? params[:user][:rolable_type].downcase
        child_class_name = params[:user][:rolable_type].downcase.camelize
        rolable_type = params[:user][:rolable_type].downcase
      else
        child_class_name = "Customer"
        rolable_type = "customer"
      end

      resource.rolable = child_class_name.constantize.new if resource.rolable.nil?
    %>
    <%= skillz_devise_error_messages! %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= fields_for resource.rolable do |rf| %>
      <% render :partial => "#{child_class_name.underscore}_fields", :locals => { :f => rf } %>
    <% end %>
    <%= hidden_field :user, :rolable_type, :value => rolable_type %>
    <%= f.submit 'Sign up', :class => 'button right' %>
  <% end %>
</div>

app/views/workers/jobs.html.erb
<h1>Jobs history</h1>
<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Customer</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
    <tr>
      <td><%= job.description %></td>
      <td><%= job.start_date %></td>
      <td><%= job.end_date %></td>
      <td><%= job.customer.name %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/workers/show.html.erb
<h1>Worker Details</h1>
<p>Name: <%= @worker.name %></p>
<p>Email: <%= @worker.user.email %></p>
<p>Skills: <%= display_skills(@worker.skills, ', ') %></p>